name: test-check
on:
  push:
    baranches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install poetry
      - run: pip install pytest
      - run: make install
      - run: make test
